import { StyleSheet } from "react-native";
import {COLORS, FONTS, SIZES} from '../../../../constants';

export default StyleSheet.create({
    container:{
        flex:1,
        marginTop:SIZES.radius,
        paddingLeft:SIZES.padding
    },
            /*Render Item */
    renderItemContainer:{
        marginVertical:SIZES.base
    },
    renderItemHomeButtonContainer:{
        flex:1,
        flexDirection:'row'
    },
    renderItemHomeImage:{
        resizeMode:'cover',
        width:80,
        height:130,
        borderRadius:10
    },
    homeButtonInnerContainer:{
        flex:1,
        marginLeft:SIZES.radius
    },
    renderItemBookTitle:{
        paddingRight:SIZES.padding,
        fontSize:17.7,
        color:COLORS.white
    },
    renderItemBookWrite:{
        ...FONTS.h3,
        color:COLORS.lightGray
    },
    renderItemIconsContainer:{
        flexDirection:'row',
        marginTop:SIZES.radius
    },
    renderItemPageFilledImage:{
        resizeMode:'contain',
        width:20,
        height:20,
        tintColor:COLORS.lightGray 
    },
    renderItemPageNoText:{
        ...FONTS.h4,
        color:COLORS.lightGray,
        paddingHorizontal:SIZES.radius
    },
    renderItemReadImage:{
        resizeMode:'contain',
        width:20,
        height:20,
        tintColor:COLORS.lightGray
    },
    renderItemReaded:{
        ...FONTS.h4,
        color:COLORS.lightGray,
        paddingHorizontal:SIZES.radius
    },
    renderItemBookType:{
        flexDirection:'row',
        marginTop:SIZES.base
    },
    adventureContainer:{
        justifyContent:'center',
        alignItems:'center',
        padding:4,
        marginRight:SIZES.base,
        backgroundColor:COLORS.darkGreen,
        height:32,
        borderRadius:SIZES.radius
    },
    adventureText:{
        ...FONTS.body4,
        color:COLORS.lightGreen  
    },
    romanceContainer:{
        justifyContent:'center',
        alignItems:'center',
        padding:4,
        marginRight:SIZES.base,
        backgroundColor:COLORS.darkRed,
        height:32,
        borderRadius:SIZES.radius
    },
    romanceText:{
        ...FONTS.body4,
        color:COLORS.lightRed
    },
    dramaContainer:{
        justifyContent:'center',
        alignItems:'center',
        padding:4,
        marginRight:6,
        backgroundColor:COLORS.darkBlue,
        height:32,
        borderRadius:SIZES.radius
    },
    dramaText:{
        ...FONTS.body4,
        color:COLORS.lightBlue
    },
    bookmarkButtonContainer:{
        position:'absolute',
        top:5,
        right:10
    },
    bookmarkImage:{
        resizeMode:'contain',
        width:20,
        height:25,
        tintColor:COLORS.lightGray
    }
})